checkpoint_dir: C:/Users/Sharjeel Mustafa/Documents/Documents/Academic/C874/C874-final-project/log/saved/
data_path: C:/Users/Sharjeel Mustafa/Documents/Documents/Academic/C874/C874-final-project/data/
dataset: ml-100k
model: LightGCN
show_progress: false
state: Info
